
import type { User, AppData, Team, Organization } from '@/types';

// This file now only contains the structure for seeding data.
// The actual data is managed in Firestore.

export const mockUsers: Omit<User, 'id'>[] = [
  { username: 'individual_user', phoneNumber: '1112223333', role: 'individual', name: 'Alex Doe', email: 'alex.doe@example.com' },
  { username: 'update_user', phoneNumber: '4445556666', role: 'update', name: 'Ben Carter', email: 'ben.carter@example.com' },
  { username: 'admin_user', phoneNumber: '7778889999', role: 'admin', name: 'Casey Smith', email: 'casey.smith@example.com' },
  { username: 'inquiry_user', phoneNumber: '1234567890', role: 'inquiry', name: 'Dana Ray', email: 'dana.ray@example.com' },
  { username: 'super_user', phoneNumber: '0000000000', role: 'super', name: 'Super Admin', email: 'super.admin@example.com' },
];

export const mockAppData: Omit<AppData, 'id'>[] = [
    { name: 'Client Onboarding Status', value: 'Phase 2', lastUpdated: '2023-10-26T10:00:00Z', updatedBy: 'Ben Carter', isFlagged: false },
    { name: 'Project Alpha Budget', value: '50000', lastUpdated: '2023-10-25T14:30:00Z', updatedBy: 'Ben Carter', isFlagged: false },
    { name: 'Server Uptime', value: '99.98', lastUpdated: '2023-10-26T11:00:00Z', updatedBy: 'System', isFlagged: false },
    { name: 'Q4 Marketing Spend', value: '15000', lastUpdated: '2023-10-24T09:15:00Z', updatedBy: 'Ben Carter', isFlagged: true },
    { name: 'Support Ticket Volume', value: '253', lastUpdated: '2023-10-26T16:45:00Z', updatedBy: 'System', isFlagged: false },
    { name: 'Active Users', value: '1250', lastUpdated: '2023-10-26T18:00:00Z', updatedBy: 'System', isFlagged: false },
];

export const mockOrganizations: Omit<Organization, 'id' | 'location'>[] = [
    { name: "St.Peter's & St.Paul's OSC, Koyambedu" },
    { name: 'St.George OSC, Padi' },
    { name: 'St.Gregorios OSC, Perambur' },
    { name: 'St.Thomas OSC, Puzhuthivakkam' },
    { name: 'Mar Gregorios OSC, Tambaram' },
    { name: "St.Mary's OSC, Thiruvottiyur" },
    { name: 'St.George OSC, Ramalingapuram' },
    { name: 'St.Thomas Cathedral, Broadway' },
    { name: "St.Mary's Cathedral, Coimbatore" },
    { name: 'St.George OSC, Avadi' },
];

// Changed `organizationId` to `organizationName` for more robust mapping during seed.
// Clearing mockTeams as they are associated with old organizations.
export const mockTeams: (Omit<Team, 'id' | 'organizationId'> & { organizationName: string })[] = [
  { type: 'mens_doubles', player1Name: 'Allen B George', player2Name: 'Rohan James', genderP1: 'male', genderP2: 'male', organizationName: 'St.George OSC, Ramalingapuram' },
  { type: 'mens_doubles', player1Name: 'Sanjan Sunil', player2Name: 'Johan Thomas', genderP1: 'male', genderP2: 'male', organizationName: 'St.Peter\'s & St.Paul\'s OSC, Koyambedu' },
  { type: 'mens_doubles', player1Name: 'Vineeth P V', player2Name: 'Shalin Sunil', genderP1: 'male', genderP2: 'male', organizationName: 'St.Peter\'s & St.Paul\'s OSC, Koyambedu' },
  { type: 'mens_doubles', player1Name: 'Ajay', player2Name: 'O J Philip', genderP1: 'male', genderP2: 'male', organizationName: 'St.George OSC, Padi' },
  { type: 'mens_doubles', player1Name: 'Ebin Thomas', player2Name: 'Ajith Jacob', genderP1: 'male', genderP2: 'male', organizationName: 'St.George OSC, Padi' },
  { type: 'mens_doubles', player1Name: 'Febin Thomas', player2Name: 'Sibin Koshy', genderP1: 'male', genderP2: 'male', organizationName: 'St.George OSC, Padi' },
  { type: 'mens_doubles', player1Name: 'Shabin T S', player2Name: 'Shijin', genderP1: 'male', genderP2: 'male', organizationName: 'St.George OSC, Padi' },
  { type: 'mens_doubles', player1Name: 'Abraham George Thomas', player2Name: 'Roshan Thomas Mathew', genderP1: 'male', genderP2: 'male', organizationName: 'St.Gregorios OSC, Perambur' },
  { type: 'mens_doubles', player1Name: 'Noble Chandy Alex', player2Name: 'Basil P Eldo', genderP1: 'male', genderP2: 'male', organizationName: 'St.Gregorios OSC, Perambur' },
  { type: 'mens_doubles', player1Name: 'Reuben Cherian', player2Name: 'Avinash George Thomas', genderP1: 'male', genderP2: 'male', organizationName: 'St.Gregorios OSC, Perambur' },
  { type: 'mens_doubles', player1Name: 'Shine P Eldo', player2Name: 'Jojy T', genderP1: 'male', genderP2: 'male', organizationName: 'St.Gregorios OSC, Perambur' },
  { type: 'mens_doubles', player1Name: 'Basil Manithottam', player2Name: 'Russel B Rex', genderP1: 'male', genderP2: 'male', organizationName: 'St.Thomas OSC, Puzhuthivakkam' },
  { type: 'mens_doubles', player1Name: 'Nevin Justy', player2Name: 'Alwyn Roy', genderP1: 'male', genderP2: 'male', organizationName: 'St.Thomas OSC, Puzhuthivakkam' },
  { type: 'mens_doubles', player1Name: 'Jijo Jose', player2Name: 'Roshan B Reji', genderP1: 'male', genderP2: 'male', organizationName: 'Mar Gregorios OSC, Tambaram' },
  { type: 'mens_doubles', player1Name: 'Remil P Babu', player2Name: 'Nathaniel Geevarghese Skariah', genderP1: 'male', genderP2: 'male', organizationName: 'Mar Gregorios OSC, Tambaram' },
  { type: 'mens_doubles', player1Name: 'Robin Varghese', player2Name: 'Subin Varghese C', genderP1: 'male', genderP2: 'male', organizationName: 'Mar Gregorios OSC, Tambaram' },
  { type: 'mens_doubles', player1Name: 'Sonu Jacob Zachariah', player2Name: 'George Steve Varghese', genderP1: 'male', genderP2: 'male', organizationName: 'Mar Gregorios OSC, Tambaram' },
  { type: 'mens_doubles', player1Name: 'Sibi', player2Name: 'Merwin', genderP1: 'male', genderP2: 'male', organizationName: 'St.Mary\'s OSC, Thiruvottiyur' },
  { type: 'mens_doubles', player1Name: 'David Babu', player2Name: 'Albin Biju', genderP1: 'male', genderP2: 'male', organizationName: 'St.Mary\'s OSC, Thiruvottiyur' },
  { type: 'mens_doubles', player1Name: 'Linosh', player2Name: 'Rohan Thomas', genderP1: 'male', genderP2: 'male', organizationName: 'St.Mary\'s OSC, Thiruvottiyur' },
  { type: 'mixed_doubles', player1Name: 'Vineeth P V', player2Name: 'Teena Thomas', genderP1: 'male', genderP2: 'female', organizationName: 'St.Peter\'s & St.Paul\'s OSC, Koyambedu' },
  { type: 'mixed_doubles', player1Name: 'Shabin T S', player2Name: 'Subitha Anoop', genderP1: 'male', genderP2: 'female', organizationName: 'St.George OSC, Padi' },
  { type: 'mixed_doubles', player1Name: 'Basil Manithottam', player2Name: 'Merlin Rachel Joy', genderP1: 'male', genderP2: 'female', organizationName: 'St.Thomas OSC, Puzhuthivakkam' },
  { type: 'mixed_doubles', player1Name: 'Nevin Justy', player2Name: 'Lincy Anna Varghese', genderP1: 'male', genderP2: 'female', organizationName: 'St.Thomas OSC, Puzhuthivakkam' },
  { type: 'mixed_doubles', player1Name: 'Remil P Babu', player2Name: 'Johnse', genderP1: 'male', genderP2: 'female', organizationName: 'Mar Gregorios OSC, Tambaram' },
  { type: 'mixed_doubles', player1Name: 'Subin Varghese', player2Name: 'Jerlin K Reji', genderP1: 'male', genderP2: 'female', organizationName: 'Mar Gregorios OSC, Tambaram' },
  { type: 'mixed_doubles', player1Name: 'Albin', player2Name: 'Vincy', genderP1: 'male', genderP2: 'female', organizationName: 'St.Mary\'s OSC, Thiruvottiyur' },
  { type: 'mixed_doubles', player1Name: 'Bijo', player2Name: 'Steffi Mary', genderP1: 'male', genderP2: 'female', organizationName: 'St.Mary\'s OSC, Thiruvottiyur' },
  { type: 'mixed_doubles', player1Name: 'Linosh', player2Name: 'Sharon Ancy', genderP1: 'male', genderP2: 'female', organizationName: 'St.Mary\'s OSC, Thiruvottiyur' },
  { type: 'womens_doubles', player1Name: 'Ancy B George', player2Name: 'Anju Susan Thomas', genderP1: 'female', genderP2: 'female', organizationName: 'St.George OSC, Ramalingapuram' },
  { type: 'womens_doubles', player1Name: 'Sarah Cherian', player2Name: 'Sheba Cherian', genderP1: 'female', genderP2: 'female', organizationName: 'St.Peter\'s & St.Paul\'s OSC, Koyambedu' },
  { type: 'womens_doubles', player1Name: 'Teena Thomas', player2Name: 'Sherine Vineeth', genderP1: 'female', genderP2: 'female', organizationName: 'St.Peter\'s & St.Paul\'s OSC, Koyambedu' },
  { type: 'womens_doubles', player1Name: 'Ancy Thomson', player2Name: 'Alisha Susan', genderP1: 'female', genderP2: 'female', organizationName: 'St.George OSC, Padi' },
  { type: 'womens_doubles', player1Name: 'Subitha Anoop', player2Name: 'Jinsi Daniel', genderP1: 'female', genderP2: 'female', organizationName: 'St.George OSC, Padi' },
  { type: 'womens_doubles', player1Name: 'Merlin Rachel Joy', player2Name: 'Lincy Anna Varghese', genderP1: 'female', genderP2: 'female', organizationName: 'St.Thomas OSC, Puzhuthivakkam' },
  { type: 'womens_doubles', player1Name: 'Jerlin K Reji', player2Name: 'Sharon Zacharia', genderP1: 'female', genderP2: 'female', organizationName: 'Mar Gregorios OSC, Tambaram' },
  { type: 'womens_doubles', player1Name: 'Sinu Jacob Zachariah', player2Name: 'Johnse Johnson', genderP1: 'female', genderP2: 'female', organizationName: 'Mar Gregorios OSC, Tambaram' },
  { type: 'womens_doubles', player1Name: 'Steffii Mary', player2Name: 'Sharon Ancy', genderP1: 'female', genderP2: 'female', organizationName: 'St.Mary\'s OSC, Thiruvottiyur' },
  { type: 'womens_doubles', player1Name: 'Vincy', player2Name: 'Sharon', genderP1: 'female', genderP2: 'female', organizationName: 'St.Mary\'s OSC, Thiruvottiyur' },
  { type: 'mens_doubles', player1Name: 'Sunjith', player2Name: 'Shaun', genderP1: 'male', genderP2: 'male', organizationName: 'St.Thomas Cathedral, Broadway' },
  { type: 'mens_doubles', player1Name: 'Thomas', player2Name: 'Immanuel', genderP1: 'male', genderP2: 'male', organizationName: 'St.Thomas Cathedral, Broadway' },
  { type: 'mens_doubles', player1Name: 'Andrew', player2Name: 'Jibu', genderP1: 'male', genderP2: 'male', organizationName: 'St.Thomas Cathedral, Broadway' },
  { type: 'womens_doubles', player1Name: 'Annette', player2Name: 'Leena', genderP1: 'female', genderP2: 'female', organizationName: 'St.Thomas Cathedral, Broadway' },
  { type: 'mixed_doubles', player1Name: 'Shine P Eldo', player2Name: 'Irene Biju', genderP1: 'male', genderP2: 'female', organizationName: 'St.Gregorios OSC, Perambur' },
  { type: 'mixed_doubles', player1Name: 'Basil P E', player2Name: 'Jenifer', genderP1: 'male', genderP2: 'female', organizationName: 'St.Gregorios OSC, Perambur' },
  { type: 'mixed_doubles', player1Name: 'Abraham', player2Name: 'Kezia John', genderP1: 'male', genderP2: 'female', organizationName: 'St.Gregorios OSC, Perambur' },
  { type: 'mixed_doubles', player1Name: 'Sunjith', player2Name: 'Annette', genderP1: 'male', genderP2: 'female', organizationName: 'St.Thomas Cathedral, Broadway' },
  { type: 'mixed_doubles', player1Name: 'Shaun', player2Name: 'Leena', genderP1: 'male', genderP2: 'female', organizationName: 'St.Thomas Cathedral, Broadway' },
  { type: 'mens_doubles', player1Name: 'Eldhow Sabu', player2Name: 'Lawrence KV', genderP1: 'male', genderP2: 'male', organizationName: 'St.Mary\'s Cathedral, Coimbatore' },
  { type: 'mens_doubles', player1Name: 'Gregery Mohan', player2Name: 'Albin Abraham', genderP1: 'male', genderP2: 'male', organizationName: 'St.George OSC, Avadi' },
  { type: 'mens_doubles', player1Name: 'Jeevan Thomas John', player2Name: 'Kenneth', genderP1: 'male', genderP2: 'male', organizationName: 'St.George OSC, Avadi' },
  { type: 'mens_doubles', player1Name: 'Sharon Thomas', player2Name: 'Jones Thomas', genderP1: 'male', genderP2: 'male', organizationName: 'St.George OSC, Avadi' },
  { type: 'mens_doubles', player1Name: 'Denis Thomas', player2Name: 'Jithin Philip', genderP1: 'male', genderP2: 'male', organizationName: 'St.George OSC, Avadi' },
  { type: 'mens_doubles', player1Name: 'Nibin', player2Name: 'Johjen', genderP1: 'male', genderP2: 'male', organizationName: 'St.George OSC, Avadi' },
  { type: 'mixed_doubles', player1Name: 'Sneha Jithin', player2Name: 'Jithin Philip', genderP1: 'female', genderP2: 'male', organizationName: 'St.George OSC, Avadi' },
  { type: 'mixed_doubles', player1Name: 'Denis Thomas', player2Name: 'Jinu Mathew', genderP1: 'male', genderP2: 'female', organizationName: 'St.George OSC, Avadi' },
  { type: 'mixed_doubles', player1Name: 'Sharon Thomas', player2Name: 'Donia Sharon', genderP1: 'male', genderP2: 'female', organizationName: 'St.George OSC, Avadi' },
  { type: 'mixed_doubles', player1Name: 'Jones Thomas', player2Name: 'Simi Sherry', genderP1: 'male', genderP2: 'female', organizationName: 'St.George OSC, Avadi' },
  { type: 'womens_doubles', player1Name: 'Jinu Mathew', player2Name: 'Sneha Jithin', genderP1: 'female', genderP2: 'female', organizationName: 'St.George OSC, Avadi' },
  { type: 'womens_doubles', player1Name: 'Kezia john', player2Name: 'Irene Biju', genderP1: 'female', genderP2: 'female', organizationName: 'St.Gregorios OSC, Perambur' },
];
